server:
  port: 8001

spring:
  application:
    name: cloud-hystrix-payment

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
     defaultZone: http://eureka-7001.com:7001/eureka #暂且用7001单机版的eureka