# 这里的Zookeeper是安装在阿里云上的
server:
  port: 8004
spring:
  application:
    name: cloud-payment-server #服务名跟其他模块保持一致
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud
    username: root
    password: 123456
  cloud:
    zookeeper:
      connect-string: 47.94.2.103:2181  #目前单机的Zookeeper，集群的话，跟Eureka一样，往后面接就行

#mybatis配置
mybatis:
  type-aliases-package: com.wang.entity
  mapper-locations: classpath:mappers/*.xml