server:
  port: 80
spring:
  application:
    name: consul-server-consumer
  cloud:
    consul:
      host: 47.94.2.103 #consul同样在阿里云上安装着
      port: 8500
      discovery:
        service-name: ${spring.application.name}
