# 服务端口号
server:
  port: 8001
spring:
  application:
    name: cloud-payment8001   #服务名
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud
    username: root
    password: 123456

eureka:
  client:
    register-with-eureka: true    # 表示是否将自己注册金Eureka注册中心
    fetch-registry: true      # 是否从已有的EurekaServer中抓取已有的注册信息，默认为true，单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
     defaultZone: http://localhost:7991/eureka

#mybatis配置
mybatis:
  type-aliases-package: com.wang.entity
  mapper-locations: classpath:mappers/*.xml
