# 服务端口号
server:
  port: 8001
spring:
  application:
    name: cloud-payment8001   #服务名
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud
    username: root
    password: 123456

#mybatis配置
mybatis:
  type-aliases-package: com.wang.entity
  mapper-locations: classpath:mappers/*.xml
