server:
  port: 9527
spring:
  application:
    name: cloud-gateway-service
  cloud:
    gateway:
      routes:
        - id: cloud-payment-server1         #路由id，没哟特定的规则，但是要唯一
          uri: http://localhost:8001        #匹配成功后要提供服务的地址
          predicates:
            - Path=/payment/get/**          #断言  如果请求路径相匹配的话进路由

        - id: cloud-payment-server2
          uri: http://localhost:8001
          predicates:
            - Path=/payment/getlb/**

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-7001.com:7001/eureka