server:
  port: 80

spring:
  application:
    name: cloud-hystrix-consumer

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-7001.com:7001/eureka #暂且用7001单机版的eureka

feign:
  hystrix:
    enabled: true  # 开启客户端降级服务